fix missing (required) index.jelly file
cause
```
org.apache.commons.jelly.JellyTagException: jar:file:/abe/jenkins/plugins/promoted-builds/WEB-INF/lib/promoted-builds.jar!/hudson/plugins/promoted_builds/PromotedBuildAction/index.jelly:111:54: <st:include> No page found 'index.jelly' for class org.jenkinsci.plugins.deployment.promoted_builds.DeploymentPromotionCondition 
```